#pragma once

#include "Definitions.h"
#include "InitializerList.h"
#include "Memory_.h"

#include "Enumerable.h"
#include "Collection.h"
#include "Math_.h"
#include "Random.h"
#include "Tuple.h"
#include "Range.h"
#include "Tie.h"
#include "Lambda.h"
#include "String_.h"
#include "Exception.h"
#include "Console.h"
#include "Environment.h"
#include "DateTime.h"
#include "UPtr.h"
#include "SPtr.h"